/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Sat Mar 14 23:03:38 2020. */

#ifndef PB_SER2NETCONFIG_PB_H_INCLUDED
#define PB_SER2NETCONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Ser2NetConfigMessage {
    uint16_t tcp_port;
/* @@protoc_insertion_point(struct:Ser2NetConfigMessage) */
} Ser2NetConfigMessage;

/* Struct field encoding specification for nanopb */
extern const pb_field_t Ser2NetConfigMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define Ser2NetConfigMessage_size                6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SER2NETCONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
