/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sat Mar 14 23:03:38 2020. */

#include "Ser2NetConfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Ser2NetConfigMessage_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Ser2NetConfigMessage, tcp_port, tcp_port, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
